POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=foo&password=bar

###
GET http://localhost:8080/auth/hello
Accept: application/json

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "foo",
  "password": "bar"
}

###

