### Register user
### Success: 200
### Failure: 401
POST {{host}}/auth/register
Content-Type: application/json

{
  "username": "foo1",
  "password": "bar222",
  "email": "mail1@example.com"
}

###

### Authenticate with credentials
### Success: 200 + Set-Cookie
### Failure: 401
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "foo1",
  "password": "bar222"
}

###

### Authenticate with session cookie
### Success: 200
### Failure: 401
GET {{host}}/auth/authenticate
Cookie: authentication={{session_id}}

###

GET {{host}}/auth/logout
Cookie: authentication={{session_id}}

###

### Send a new image
### (send with authentication cookie to save an uploader info)
### Success: 200 + body
### Failure: 401
### Error: 503
POST http://{{host}}/img/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"

< ./../../test.jpg
--WebAppBoundary
Content-Disposition: form-data; name="metadata"
Content-Type: application/json

{
    "title": "test",
    "public": true
}

--WebAppBoundary--
###

### Get an image
### Success: 200 + file stream
### Failure: 404
### Error: 503
GET http://{{host}}/img/i/{{token}}

###

### Post a comment
### Success: 200
### Failure: 401, 404
PUT http://{{host}}/comment/{{imageToken}}
Cookie: authentication={{session_id}}
Content-Type: text/plain

test comment 123456
###

### Get comments for image
### Success: 200 + json
### Failure: 404
GET http://{{host}}/comment/{{imageToken}}